---
version: 2
updates:
  - package-ecosystem: pip
    directory: /.config/
    schedule:
      day: sunday
      interval: weekly
    labels:
      - dependabot-deps-updates
      - skip-changelog
    versioning-strategy: lockfile-only
    groups:
      runtime:
        patterns:
          - ansible-core
          - pytest
      dev:
        patterns:
          - "*"
        exclude-patterns:
          - ansible-core
          - pytest
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "skip-changelog"
