sudo: false
language: python
sudo: required # needed for test_become
env:
    - TOXENV=py27-ansible_v19
    - TOXENV=py27-ansible_v22
    - TOXENV=py27-ansible_v23
    - TOXENV=py27-ansible_devel
install:
    - pip install -r test-requirements.txt
script:
    - tox
before_script:
    - TOXENV=lint tox
after_success:
    - TOXENV=coveralls tox
addons:
  apt_packages:
    - pandoc
